#!/usr/bin/env node
// Wetnose template: apply a user-supplied color palette at build time.
//
// Reads WETNOSE_COLOR_PALETTE (a JSON object with 8 hex colors) from the
// environment and writes src/styles/palette.css with a Tailwind v4 @theme
// block that overrides this template's defaults. When the env var is absent
// or empty, an empty file is written so the template's own colors win.
//
// This script is intentionally dependency-free so it can run in CI without
// touching the rest of the build graph. Math kept in sync with
// shared/src/color/palette.ts in the wetnose monorepo.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "..", "src", "styles", "palette.css");

const TOKENS = [
  "background",
  "foreground",
  "primary",
  "secondary",
  "accent",
  "muted",
  "border",
  "destructive",
];

function main() {
  const raw = process.env.WETNOSE_COLOR_PALETTE;
  mkdirSync(dirname(OUT), { recursive: true });

  if (!raw || raw.trim() === "" || raw === "null") {
    writeFileSync(OUT, "/* No custom palette set; template defaults apply. */\n");
    console.log("[apply-palette] no WETNOSE_COLOR_PALETTE set — using template defaults");
    return;
  }

  let palette;
  try {
    palette = JSON.parse(raw);
  } catch (err) {
    console.error("[apply-palette] WETNOSE_COLOR_PALETTE is not valid JSON:", err.message);
    process.exit(1);
  }

  for (const token of TOKENS) {
    if (typeof palette[token] !== "string" || !/^#[0-9a-f]{6}$/i.test(palette[token])) {
      console.error(`[apply-palette] missing or invalid hex for token: ${token}`);
      process.exit(1);
    }
  }

  const css = renderPaletteCss(palette);
  writeFileSync(OUT, css);
  console.log(`[apply-palette] wrote ${OUT}`);
}

function renderPaletteCss(p) {
  const lines = ["/* Generated by apply-palette.mjs — do not edit. */", "@theme {"];
  const push = (k, v) => lines.push(`  --color-${k}: ${v};`);

  // User-editable surfaces.
  for (const t of TOKENS) push(t, formatOklch(hexToOklch(p[t])));

  // Derived tokens. Kept in sync with the Wetnose theme contract:
  //   *-foreground pairs are auto contrast-flipped for each surface.
  //   card / popover follow background.
  //   input follows border, ring follows primary.
  //   muted-foreground is a desaturated mid-grey relative to foreground.
  const fg = (bg) => formatOklch(hexToOklch(pickReadableForeground(bg)));
  push("background-foreground", fg(p.background));
  push("foreground-background", formatOklch(hexToOklch(p.background)));
  push("primary-foreground", fg(p.primary));
  push("secondary-foreground", fg(p.secondary));
  push("accent-foreground", fg(p.accent));
  push("destructive-foreground", fg(p.destructive));
  push("card", formatOklch(hexToOklch(p.background)));
  push("card-foreground", fg(p.background));
  push("popover", formatOklch(hexToOklch(p.background)));
  push("popover-foreground", fg(p.background));
  push("input", formatOklch(hexToOklch(p.border)));
  push("ring", formatOklch(hexToOklch(p.primary)));

  // muted-foreground: take foreground, lift L toward middle, halve C.
  const fgOk = hexToOklch(p.foreground);
  push(
    "muted-foreground",
    formatOklch({ l: Math.min(0.55, fgOk.l + 0.3), c: fgOk.c * 0.5, h: fgOk.h }),
  );

  lines.push("}", "");
  return lines.join("\n");
}

// ---------- OKLab / OKLch math (mirrors shared/src/color/palette.ts) ----------

function srgbToLinear(s) {
  return s <= 0.04045 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
}
function linearToSrgb(s) {
  return s <= 0.0031308 ? 12.92 * s : 1.055 * Math.pow(s, 1 / 2.4) - 0.055;
}
function hexToRgb(hex) {
  const m = hex.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i);
  return [parseInt(m[1], 16) / 255, parseInt(m[2], 16) / 255, parseInt(m[3], 16) / 255];
}
function hexToOklch(hex) {
  const [r, g, b] = hexToRgb(hex).map(srgbToLinear);
  const l_ = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m_ = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s_ = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_;
  const a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_;
  const bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_;
  let h = (Math.atan2(bb, a) * 180) / Math.PI;
  if (h < 0) h += 360;
  return { l: L, c: Math.sqrt(a * a + bb * bb), h };
}
function formatOklch({ l, c, h }) {
  const r = (n, d) => Number.parseFloat(n.toFixed(d));
  return `oklch(${r(l, 4)} ${r(c, 4)} ${r(h, 2)})`;
}
function relativeLuminance(hex) {
  const [r, g, b] = hexToRgb(hex).map(srgbToLinear);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrastRatio(fg, bg) {
  const a = relativeLuminance(fg);
  const b = relativeLuminance(bg);
  return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
}
function pickReadableForeground(bg) {
  return contrastRatio("#ffffff", bg) >= contrastRatio("#111111", bg) ? "#ffffff" : "#111111";
}

main();
